name: Conditional Commit Job

on: push

jobs:
  read-config:
    name: Read Config
    runs-on: ubuntu-latest
    outputs:
      owners: ${{ steps.get-owners.outputs.owners }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Read owners from config.yml
        id: get-owners
        run: |
          owners=$(yq '.owners | join(",")' config.yml)
          echo "::set-output name=owners::$owners"

  commit-job:
    name: Commit Job
    runs-on: ubuntu-latest
    needs: read-config
    if: contains(needs.read-config.outputs.owners, 'siri-chevuri')
    steps:
      - name: Run job if "siri-chevuri" is in the owners list
        run: echo "siri-chevuri is in the owners list, running commit job."
