name: Conditional Commit Job

on: push

jobs:
  read-config:
    name: Read Config
    runs-on: ubuntu-latest
    outputs:
      owners: ${{ steps.get-owners.outputs.owners }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated to use the latest version

      - name: Verify config.yml exists
        run: |
          if [ ! -f .github/workflows/config.yml ]; then
            echo "config.yml not found!"
            exit 1
          fi

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Read owners from config.yml
        id: get-owners
        run: |
          owners=$(yq eval '.owners | join(",")' .github/workflows/config.yml)
          echo "owners=$owners" >> $GITHUB_ENV  # Use environment files to set the output variable

  commit-job:
    name: Commit Job
    runs-on: ubuntu-latest
    needs: read-config
    if: contains(needs.read-config.outputs.owners, 'siri-chevuri')
    steps:
      - name: Run job if "siri-chevuri" is in the owners list
        run: echo "siri-chevuri is in the owners list, running commit job."
