name: POD Backend Pipeline for Feature Branches

on:
  push:
    branches: 
        - master

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write
  
jobs:
  selenium-tests:
    name: 'Run Selenium Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Download ChromeDriver
        run: |
          sudo apt-get install -y curl
          chrome_version=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          chrome_major_version=$(echo $chrome_version | cut -d '.' -f 1)
          echo "Chrome version: $chrome_version, Major version: $chrome_major_version"
          chromedriver_version=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chrome_major_version")
          if [[ $chromedriver_version == *NoSuchKey* ]]; then
            chromedriver_version=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          fi
          echo "ChromeDriver version: $chromedriver_version"
          wget -N "https://chromedriver.storage.googleapis.com/$chromedriver_version/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d $HOME/.local/bin
          rm chromedriver_linux64.zip

      - name: Install Maven dependencies
        run: mvn -B dependency:resolve dependency:resolve-plugins

      - name: Run Selenium tests
        run: mvn test

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: selenium-test-results
          path: tests/selenium/target/surefire-reports/
