name: Selenium Tests

on:
  push:
    branches: 
      - selenium

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  selenium-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install

    - name: Download and install Internet Explorer Driver
      run: |
        curl -L -o IEDriverServer.zip https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.1.0/IEDriverServer_Win32_4.1.0.zip
        Expand-Archive -Path IEDriverServer.zip -DestinationPath $env:TEMP
        Move-Item -Path "$env:TEMP/IEDriverServer.exe" -Destination "C:/Windows/System32/IEDriverServer.exe"

    - name: Run Selenium tests
      run: mvn test

    - name: Archive test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/surefire-reports/
