name: Selenium Tests

on:
  push:
    branches: 
      - selenium

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install

    - name: Install Firefox and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 xvfb

    - name: Install specific version of Geckodriver
      run: |
        GECKODRIVER_VERSION="v0.31.0"
        wget "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
        tar -xzf "geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
        sudo mv geckodriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/geckodriver

    - name: Verify Firefox and Geckodriver versions
      run: |
        echo "Firefox version:"
        firefox --version
        echo "Geckodriver version:"
        geckodriver --version

    - name: Start Xvfb
      run: |
        Xvfb :99 -ac &
        export DISPLAY=:99
        echo "Starting Xvfb"
        sleep 5
        echo "Xvfb started"

    - name: Run Selenium tests
      run: |
        echo "Running tests"
        mvn test
        echo "Tests completed"

    - name: Archive test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/surefire-reports/
